[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"