# Generated by Django 6.0.5 on 2026-05-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('converted', models.DecimalField(decimal_places=4, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conversion',
                'verbose_name_plural': 'Historique des conversions',
                'ordering': ['-created_at'],
            },
        ),
    ]
